deb3

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -12,3 +12,7 @@ systemctl restart nginx
 
 systemctl enable nginx
 HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost)
+if [ "$HTTP_CODE" -ne 200 ]; then
+    echo "Error: Nginx is not returning HTTP 200"
+    exit 1
+fi
